USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/lenovo/a820/BoardConfigVendor.mk

TARGET_ARCH := arm
ARCH_ARM_HAVE_VFP := true
ARCH_ARM_HAVE_NEON := true
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a9
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := a820
TARGET_OTA_ASSERT_DEVICE := a820

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
TARGET_PREBUILT_KERNEL := device/lenovo/a820/kernel

# EGL
BOARD_EGL_CFG := device/lenovo/a820/egl.cfg
USE_OPENGL_RENDERER := true
TARGET_FORCE_CPU_UPLOAD := true

# fix this up by examining /proc/mtd on a running device
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 6291456
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 6291456
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 629145600
BOARD_USERDATAIMAGE_PARTITION_SIZE := 713031680
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PROVIDES_INIT := true
TARGET_PROVIDES_INIT_TARGET_RC := true
TARGET_RECOVERY_FSTAB := device/lenovo/a820/recovery.fstab


# Internal storage
BOARD_HAS_SDCARD_INTERNAL := true
BOARD_SDCARD_DEVICE_PRIMARY := /dev/block/mmcblk1p1
BOARD_SDCARD_DEVICE_SECONDARY := /dev/block/mmcblk1
BOARD_SDEXT_DEVICE := /dev/block/mmcblk1p1


BOARD_HAS_NO_SELECT_BUTTON := true

BOARD_USE_USB_MASS_STORAGE_SWITCH := true

BOARD_USES_AUDIO_LEGACY := true

#HAVE_HTC_AUDIO_DRIVER := true
BOARD_USES_YUSU_AUDIO := true

BOARD_AGPS_SUPL_LIBRARIES := true
BOARD_GPS_LIBRARIES := true


TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true

ADDITIONAL_DEFAULT_PROPERTIES += \
    ro.secure=0 \
    service.adb.enable=1 \
    sys.usb.config=adb

